#Mahika Bagri 
#30 March 2026

logging:
  level:
    org:
      springframework:
        security: DEBUG
        
spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SUPPORT_EMAIL}
    password: ${APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  config:
    import: "optional:file:.env[.properties]"

security:
  jwt:
    secret-key: ${SECRET_KEY}
    expiration-time: 36000
    
server:
  port: 8080